"""Constants for the Yeelight Night Mode integration."""

DOMAIN = "yeelight_night_mode"
SCAN_INTERVAL_SECONDS = 30
CONF_HOST = "host"

CONF_ENTITY_TYPE = "entity_type"
ENTITY_TYPE_SWITCH = "switch"
ENTITY_TYPE_LIGHT = "light"
ENTITY_TYPES = [ENTITY_TYPE_SWITCH, ENTITY_TYPE_LIGHT]

CONF_ENTITY_NAME_MODE = "entity_name_mode"
CONF_CUSTOM_ENTITY_NAME = "custom_entity_name"

CONF_ENTITY_DISPLAY_NAME_MODE = "entity_display_name_mode"
CONF_CUSTOM_ENTITY_DISPLAY_NAME = "custom_entity_display_name"
ENTITY_DISPLAY_NAME_MODE_DEFAULT = "default"
ENTITY_DISPLAY_NAME_MODE_CUSTOM = "custom"
ENTITY_DISPLAY_NAME_MODES = [
    ENTITY_DISPLAY_NAME_MODE_DEFAULT,
    ENTITY_DISPLAY_NAME_MODE_CUSTOM,
]
ENTITY_NAME_MODE_NIGHT_SENSOR = "night_sensor"
ENTITY_NAME_MODE_CUSTOM = "custom"
ENTITY_NAME_MODES = [
    ENTITY_NAME_MODE_NIGHT_SENSOR,
    ENTITY_NAME_MODE_CUSTOM,
]
